Repository pay-theory/payment-components, pull requests merged in 2023-07, with the labels that each got.

#300 v2.16.0 changes
  package-lock.json
  package.json
  src/common/dom.ts
  src/common/format.ts
  src/common/network.ts
  src/common/pay_theory_types.ts
  src/components/pay-theory-hosted-field-transactional/index.ts
  src/components/pay-theory-hosted-field/index.ts
Labels: large, waiting-for-review

#301 v2.16.0 changes
  src/common/format.ts
  src/common/pay_theory_types.ts
Labels: small, waiting-for-review, services

#309 fix: v2.15.8
  src/components/pay-theory-hosted-field-transactional/index.ts
  src/field-set/actions.ts
Labels: small, waiting-for-review

#311 changes
  src/components/pay-theory-hosted-field-transactional/index.ts
  src/field-set/actions.ts
Labels: small, waiting-for-review, services

#312 Hotfix/capture observer
  src/components/pay-theory-hosted-field-transactional/index.ts
  src/field-set/actions.ts
Labels: small, waiting-for-review, services
